/**
 * AEGIS — Hardcoded CICIDS 2017 Demo Dataset
 * Works 100% without any backend connection.
 */
import type { ScanResult } from './services/api';

export const DEMO_SCAN_ID = 'demo-cicids-2017';

export const MOCK_SCAN_RESULT: ScanResult = {
  scan_id: DEMO_SCAN_ID,
  timestamp: '2026-04-10T09:30:00Z',
  filename: 'CICIDS-2017-sample.csv',
  metrics: {
    total_threats: 15,
    critical_count: 5,
    medium_count: 5,
    low_count: 5,
    unique_ips: 11,
    scan_duration: 8.7,
    overall_threat_score: 87,
    overall_severity: 'CRITICAL',
  },
  commander_brief: {
    lines: [
      'Multiple coordinated brute-force SSH campaigns detected from Eastern European and Asian threat actors targeting critical authentication services on ports 22 and 3389.',
      'Active data exfiltration confirmed — 4.7 GB transferred to known C2 infrastructure at 91.219.236.222 via encrypted reverse shell on port 4444. Immediate containment required.',
      'Distributed denial-of-service flood pattern identified from botnet cluster across 3 source IPs. Recommend activating AEGIS automated defence protocols and escalating to SOC Level 3.',
    ],
    operation_id: 'AEGIS-7F3A2B',
    generated_at: '2026-04-10T09:30:08Z',
    classification: 'CLASSIFIED',
  },
  threats: [
    // ── 5 CRITICAL ──
    {
      id: 1,
      timestamp: '2026-04-10T02:33:22',
      source_ip: '91.219.236.222',
      dest_ip: '10.0.0.5',
      protocol: 'TCP',
      bytes_transferred: 4718592000,
      threat_type: 'Reverse Shell — C2 Callback',
      mitre_code: 'T1059.004',
      mitre_technique: 'Command and Scripting Interpreter: Unix Shell',
      mitre_tactic: 'Execution',
      severity: 'CRITICAL',
      severity_score: 98,
      description: 'Outbound reverse shell connection established to known command-and-control server. Attacker gained interactive terminal access to the compromised host.',
      ai_explanation: 'This event represents a confirmed compromise. The internal host 10.0.0.5 initiated an outbound TCP connection to 91.219.236.222 on port 4444 — a classic reverse shell pattern. The attacker now has full interactive command execution capability. The 4.7 GB data transfer suggests active exfiltration of sensitive files. Immediate isolation of the affected host and forensic imaging are critical.',
      recommended_actions: [
        'IMMEDIATE: Isolate host 10.0.0.5 from the network and begin forensic imaging',
        'Block egress traffic to 91.219.236.222 at the perimeter firewall',
        'Scan all hosts for similar C2 beaconing patterns using IOC 91.219.236.222:4444',
      ],
      country: 'Russia',
      city: 'Moscow',
      isp: 'OVH SAS',
      lat: 55.7558,
      lon: 37.6173,
    },
    {
      id: 2,
      timestamp: '2026-04-10T02:34:05',
      source_ip: '185.220.101.42',
      dest_ip: '10.0.0.1',
      protocol: 'TCP',
      bytes_transferred: 5046272000,
      threat_type: 'Data Exfiltration',
      mitre_code: 'T1041',
      mitre_technique: 'Exfiltration Over C2 Channel',
      mitre_tactic: 'Exfiltration',
      severity: 'CRITICAL',
      severity_score: 96,
      description: 'Massive data transfer (4.7 GB) detected over an established C2 channel to a known Tor exit node. Indicates active exfiltration of sensitive data.',
      ai_explanation: 'A sustained high-bandwidth connection from the internal server 10.0.0.1 transferred approximately 4.7 GB to a known Tor exit node operated by a threat actor in Germany. The volume and destination strongly indicate deliberate data theft rather than legitimate traffic. The data was likely staged before transfer given the transfer speed.',
      recommended_actions: [
        'IMMEDIATE: Terminate all connections to 185.220.101.42 and block at perimeter',
        'Identify what data was exfiltrated by reviewing file access logs on 10.0.0.1',
        'Engage incident response team for breach notification assessment',
      ],
      country: 'Germany',
      city: 'Frankfurt',
      isp: 'Hetzner Online',
      lat: 50.1109,
      lon: 8.6821,
    },
    {
      id: 3,
      timestamp: '2026-04-10T02:36:12',
      source_ip: '218.92.0.107',
      dest_ip: '10.0.0.1',
      protocol: 'TCP',
      bytes_transferred: 892160,
      threat_type: 'HTTP Flood DDoS',
      mitre_code: 'T1498.001',
      mitre_technique: 'Network Denial of Service: Direct Network Flood',
      mitre_tactic: 'Impact',
      severity: 'CRITICAL',
      severity_score: 91,
      description: 'High-volume HTTP GET flood targeting web services on port 80. Over 50,000 requests per minute from a single source IP in a known botnet cluster.',
      ai_explanation: 'This is a volumetric DDoS attack using HTTP GET floods. The source IP 218.92.0.107 is part of a known Chinese botnet infrastructure. The attack rate of 50K+ requests/minute will overwhelm application-layer resources. The attack pattern shows randomized User-Agent headers, indicating bot sophistication.',
      recommended_actions: [
        'Enable rate limiting on the web application firewall (WAF)',
        'Activate DDoS mitigation service and add 218.92.0.107 to blackhole routing',
        'Monitor for additional botnet IPs joining the attack cluster',
      ],
      country: 'China',
      city: 'Nanjing',
      isp: 'Chinanet',
      lat: 32.0603,
      lon: 118.7969,
    },
    {
      id: 4,
      timestamp: '2026-04-10T02:37:44',
      source_ip: '103.75.190.11',
      dest_ip: '10.0.0.1',
      protocol: 'TCP',
      bytes_transferred: 245760,
      threat_type: 'SMB Exploit Attempt',
      mitre_code: 'T1210',
      mitre_technique: 'Exploitation of Remote Services',
      mitre_tactic: 'Lateral Movement',
      severity: 'CRITICAL',
      severity_score: 89,
      description: 'SMB exploitation attempt on port 445 using EternalBlue-variant payload. Attacker attempting lateral movement through network file sharing vulnerability.',
      ai_explanation: 'The source IP 103.75.190.11 is scanning for and attempting to exploit the SMB service on port 445. The payload signature matches EternalBlue variants (MS17-010), which remain one of the most dangerous network-level exploits. If successful, the attacker gains SYSTEM-level access without authentication. This is a precursor to ransomware deployment.',
      recommended_actions: [
        'IMMEDIATE: Verify MS17-010 patches are applied on all Windows hosts',
        'Block SMB (port 445) at the perimeter firewall for external traffic',
        'Scan for lateral movement indicators on internal network segments',
      ],
      country: 'Vietnam',
      city: 'Ho Chi Minh City',
      isp: 'VNPT',
      lat: 10.8231,
      lon: 106.6297,
    },
    {
      id: 5,
      timestamp: '2026-04-10T02:38:55',
      source_ip: '45.155.205.233',
      dest_ip: '10.0.0.12',
      protocol: 'TCP',
      bytes_transferred: 163840,
      threat_type: 'SQL Injection Attack',
      mitre_code: 'T1190',
      mitre_technique: 'Exploit Public-Facing Application',
      mitre_tactic: 'Initial Access',
      severity: 'CRITICAL',
      severity_score: 88,
      description: 'Automated SQL injection attack targeting web application on port 443. Multiple UNION-based and blind SQLi payloads detected in rapid succession.',
      ai_explanation: 'An automated SQLi scanner from 45.155.205.233 is probing the web application with a high volume of injection payloads including UNION SELECT, time-based blind, and error-based techniques. The attack targets authentication endpoints and data retrieval APIs. If the application lacks parameterized queries, database compromise is likely.',
      recommended_actions: [
        'Review WAF logs for successful injection attempts and patch vulnerable endpoints',
        'Ensure all database queries use parameterized statements / prepared queries',
        'Block 45.155.205.233 and review application logs for data access anomalies',
      ],
      country: 'Netherlands',
      city: 'Amsterdam',
      isp: 'DigitalOcean',
      lat: 52.3676,
      lon: 4.9041,
    },

    // ── 5 MEDIUM ──
    {
      id: 6,
      timestamp: '2026-04-10T02:31:47',
      source_ip: '185.220.101.42',
      dest_ip: '10.0.0.1',
      protocol: 'TCP',
      bytes_transferred: 2048,
      threat_type: 'SSH Brute Force',
      mitre_code: 'T1110.001',
      mitre_technique: 'Brute Force: Password Guessing',
      mitre_tactic: 'Credential Access',
      severity: 'MEDIUM',
      severity_score: 72,
      description: 'Repeated SSH authentication failures from a known Tor exit node. Over 200 login attempts in 60 seconds targeting root and admin accounts.',
      ai_explanation: 'A brute-force password attack against the SSH service on port 22. The source IP is a well-known Tor exit node frequently associated with credential stuffing campaigns. The attack rate of 200+ attempts per minute with common username/password combinations suggests an automated tool like Hydra or Medusa.',
      recommended_actions: [
        'Implement fail2ban or equivalent rate limiting on SSH',
        'Disable password authentication and enforce SSH key-based auth',
        'Consider moving SSH to a non-standard port and enabling port knocking',
      ],
      country: 'Germany',
      city: 'Frankfurt',
      isp: 'Hetzner Online',
      lat: 50.1109,
      lon: 8.6821,
    },
    {
      id: 7,
      timestamp: '2026-04-10T02:35:01',
      source_ip: '5.188.86.172',
      dest_ip: '10.0.0.25',
      protocol: 'TCP',
      bytes_transferred: 4096,
      threat_type: 'RDP Brute Force',
      mitre_code: 'T1110.003',
      mitre_technique: 'Brute Force: Password Spraying',
      mitre_tactic: 'Credential Access',
      severity: 'MEDIUM',
      severity_score: 68,
      description: 'Password spraying attack against Remote Desktop Protocol service on port 3389. Attacker testing common passwords across multiple accounts.',
      ai_explanation: 'This RDP brute force attack from a Russian IP tests a small set of common passwords against many user accounts — a password spraying technique designed to avoid account lockout thresholds. RDP is one of the most targeted protocols for initial access in ransomware attacks.',
      recommended_actions: [
        'Enable Network Level Authentication (NLA) on all RDP services',
        'Implement account lockout policies and multi-factor authentication',
        'Restrict RDP access to VPN-only connections',
      ],
      country: 'Russia',
      city: 'St. Petersburg',
      isp: 'Petersburg Internet Network',
      lat: 59.9343,
      lon: 30.3351,
    },
    {
      id: 8,
      timestamp: '2026-04-10T02:39:30',
      source_ip: '194.26.29.65',
      dest_ip: '10.0.0.1',
      protocol: 'TCP',
      bytes_transferred: 8192,
      threat_type: 'Port Scanning — Full TCP',
      mitre_code: 'T1046',
      mitre_technique: 'Network Service Discovery',
      mitre_tactic: 'Discovery',
      severity: 'MEDIUM',
      severity_score: 62,
      description: 'Full TCP port scan (SYN sweep) across all 65,535 ports detected from a known reconnaissance IP. Pre-attack enumeration phase.',
      ai_explanation: 'A comprehensive SYN scan is mapping all open TCP ports on the target host. This is typically the first phase of a multi-stage attack, gathering intelligence about running services before exploiting vulnerabilities. The source IP has been flagged in multiple threat intelligence feeds.',
      recommended_actions: [
        'Review firewall rules to minimize exposed ports',
        'Log and monitor for follow-up exploitation attempts from this IP',
        'Deploy honeypots on commonly scanned ports to detect further reconnaissance',
      ],
      country: 'Romania',
      city: 'Bucharest',
      isp: 'M247 Ltd',
      lat: 44.4268,
      lon: 26.1025,
    },
    {
      id: 9,
      timestamp: '2026-04-10T02:40:15',
      source_ip: '162.142.125.10',
      dest_ip: '10.0.0.8',
      protocol: 'TCP',
      bytes_transferred: 3072,
      threat_type: 'Web Application Scanning',
      mitre_code: 'T1595.002',
      mitre_technique: 'Active Scanning: Vulnerability Scanning',
      mitre_tactic: 'Reconnaissance',
      severity: 'MEDIUM',
      severity_score: 58,
      description: 'Automated vulnerability scanner probing web application for common CVEs including Log4Shell, Spring4Shell, and directory traversal.',
      ai_explanation: 'An automated vulnerability scanner is probing the web application with payloads targeting known CVEs. The scan includes Log4Shell (CVE-2021-44228), Spring4Shell, and various directory traversal patterns. While this is reconnaissance activity, it often precedes targeted exploitation.',
      recommended_actions: [
        'Verify all web application dependencies are patched against known CVEs',
        'Review WAF rules and ensure Log4Shell / Spring4Shell signatures are active',
        'Rate-limit requests from 162.142.125.10 at the load balancer',
      ],
      country: 'United States',
      city: 'Ann Arbor',
      isp: 'Censys Inc.',
      lat: 42.2808,
      lon: -83.743,
    },
    {
      id: 10,
      timestamp: '2026-04-10T02:41:00',
      source_ip: '80.82.77.139',
      dest_ip: '10.0.0.1',
      protocol: 'TCP',
      bytes_transferred: 5120,
      threat_type: 'FTP Anonymous Login Attempt',
      mitre_code: 'T1078.001',
      mitre_technique: 'Valid Accounts: Default Accounts',
      mitre_tactic: 'Persistence',
      severity: 'MEDIUM',
      severity_score: 55,
      description: 'Attempted FTP login using anonymous and default credentials on port 21. Attacker probing for misconfigured file transfer services.',
      ai_explanation: 'The attacker is testing for anonymous FTP access and default credentials (admin/admin, ftp/ftp). Misconfigured FTP services are frequently exploited for malware hosting or data exfiltration staging. This IP is associated with the Shadowserver scanning project but may be spoofed.',
      recommended_actions: [
        'Disable anonymous FTP access immediately if enabled',
        'Migrate to SFTP or SCP for all file transfer operations',
        'Audit all service accounts for default or weak credentials',
      ],
      country: 'Netherlands',
      city: 'Amsterdam',
      isp: 'Ecatel LTD',
      lat: 52.3676,
      lon: 4.9041,
    },

    // ── 5 LOW ──
    {
      id: 11,
      timestamp: '2026-04-10T02:32:01',
      source_ip: '10.0.0.5',
      dest_ip: '8.8.8.8',
      protocol: 'UDP',
      bytes_transferred: 512,
      threat_type: 'Unusual DNS Query Volume',
      mitre_code: 'T1071.004',
      mitre_technique: 'Application Layer Protocol: DNS',
      mitre_tactic: 'Command and Control',
      severity: 'LOW',
      severity_score: 35,
      description: 'Elevated DNS query volume from internal host to external resolver. Could indicate DNS tunneling or C2 communication over DNS.',
      ai_explanation: 'While DNS queries to 8.8.8.8 are normal, the volume of 500+ queries per minute from a single host is anomalous. This pattern can indicate DNS tunneling — a technique where data is exfiltrated by encoding it in DNS queries. However, it could also be legitimate software behavior.',
      recommended_actions: [
        'Monitor DNS query patterns for encoded or unusually long subdomain names',
        'Implement internal DNS filtering and log all DNS requests',
        'Investigate what application on 10.0.0.5 is generating excessive queries',
      ],
      country: 'Internal',
      city: 'Local Network',
      isp: 'Internal',
      lat: 0,
      lon: 0,
    },
    {
      id: 12,
      timestamp: '2026-04-10T02:34:33',
      source_ip: '10.0.0.12',
      dest_ip: '129.6.15.28',
      protocol: 'UDP',
      bytes_transferred: 256,
      threat_type: 'NTP Amplification Probe',
      mitre_code: 'T1498.002',
      mitre_technique: 'Network Denial of Service: Reflection Amplification',
      mitre_tactic: 'Impact',
      severity: 'LOW',
      severity_score: 30,
      description: 'NTP monlist request detected that could be used for amplification attacks. Internal host may be participating in reflected DDoS.',
      ai_explanation: 'The internal host sent an NTP monlist request, which is a deprecated command that returns a large response. If the source IP is spoofed, this host could be an unwitting participant in a DDoS reflection attack. More likely, this is a legitimate NTP sync that should still be hardened.',
      recommended_actions: [
        'Disable NTP monlist command on all NTP servers (restrict noquery)',
        'Update NTP to latest version with monlist disabled by default',
        'Monitor for spoofed source addresses in outbound NTP traffic',
      ],
      country: 'United States',
      city: 'Gaithersburg',
      isp: 'NIST',
      lat: 39.1434,
      lon: -77.2014,
    },
    {
      id: 13,
      timestamp: '2026-04-10T02:42:10',
      source_ip: '10.0.0.25',
      dest_ip: '151.101.1.140',
      protocol: 'TCP',
      bytes_transferred: 1024,
      threat_type: 'Suspicious TLS Certificate',
      mitre_code: 'T1573.002',
      mitre_technique: 'Encrypted Channel: Asymmetric Cryptography',
      mitre_tactic: 'Command and Control',
      severity: 'LOW',
      severity_score: 28,
      description: 'TLS connection established with a certificate that has a recently issued wildcard domain. Could indicate C2 communication using encrypted channels.',
      ai_explanation: 'The TLS handshake completed successfully but the server certificate was issued less than 24 hours ago for a wildcard domain — a common pattern in phishing and C2 infrastructure. While this could be legitimate (e.g., a new deployment), it warrants investigation given the timing.',
      recommended_actions: [
        'Inspect the destination domain and certificate issuer for legitimacy',
        'Add certificate transparency monitoring for new domains',
        'Cross-reference the domain against threat intelligence feeds',
      ],
      country: 'United States',
      city: 'San Francisco',
      isp: 'Fastly Inc.',
      lat: 37.7749,
      lon: -122.4194,
    },
    {
      id: 14,
      timestamp: '2026-04-10T02:43:00',
      source_ip: '10.0.0.100',
      dest_ip: '198.51.100.1',
      protocol: 'TCP',
      bytes_transferred: 2048,
      threat_type: 'Cleartext Credential Transmission',
      mitre_code: 'T1552.001',
      mitre_technique: 'Unsecured Credentials: Credentials in Files',
      mitre_tactic: 'Credential Access',
      severity: 'LOW',
      severity_score: 25,
      description: 'HTTP Basic Authentication detected over unencrypted connection. Credentials transmitted in cleartext are vulnerable to interception.',
      ai_explanation: 'An internal host is authenticating to an external service using HTTP Basic Auth over an unencrypted HTTP connection. Any network observer between the hosts can intercept the base64-encoded (but not encrypted) credentials. This is a security hygiene issue that should be remediated.',
      recommended_actions: [
        'Migrate all authentication endpoints to HTTPS',
        'Implement HSTS headers to prevent downgrade attacks',
        'Rotate any credentials that have been transmitted in cleartext',
      ],
      country: 'Internal',
      city: 'Local Network',
      isp: 'Internal',
      lat: 0,
      lon: 0,
    },
    {
      id: 15,
      timestamp: '2026-04-10T02:44:30',
      source_ip: '10.0.0.8',
      dest_ip: '142.250.80.46',
      protocol: 'TCP',
      bytes_transferred: 768,
      threat_type: 'ICMP Tunnel Suspected',
      mitre_code: 'T1095',
      mitre_technique: 'Non-Application Layer Protocol',
      mitre_tactic: 'Command and Control',
      severity: 'LOW',
      severity_score: 22,
      description: 'Unusual ICMP echo request/reply pattern with large payload sizes. May indicate data exfiltration via ICMP tunneling.',
      ai_explanation: 'ICMP packets with payloads exceeding 64 bytes were detected in a regular pattern. While normal ping uses small payloads, ICMP tunneling tools like icmpsh encode data in the payload field. The regularity of the pattern is suspicious but could also be a network monitoring tool.',
      recommended_actions: [
        'Inspect ICMP payload contents for encoded data patterns',
        'Implement ICMP payload size restrictions at the firewall',
        'Monitor for tools like icmpsh, ptunnel, or icmptunnel on internal hosts',
      ],
      country: 'United States',
      city: 'Mountain View',
      isp: 'Google LLC',
      lat: 37.386,
      lon: -122.0838,
    },
  ],
  attack_types: {
    'Reverse Shell': 12,
    'Data Exfiltration': 8,
    'DDoS / HTTP Flood': 45,
    'SMB Exploit': 18,
    'SQL Injection': 32,
    'SSH Brute Force': 120,
    'RDP Brute Force': 85,
    'Port Scanning': 67,
    'Web App Scanning': 42,
    'FTP Default Creds': 15,
    'DNS Tunneling': 5,
    'NTP Amplification': 3,
    'Suspicious TLS': 9,
    'Cleartext Auth': 22,
    'ICMP Tunnel': 2,
  },
  timeline: [], // Will be populated below
};

// Timeline is just the threats sorted by timestamp
MOCK_SCAN_RESULT.timeline = [...MOCK_SCAN_RESULT.threats].sort(
  (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
);
